// NewsLetter
export const SAVE_NWESLETTER_QUERY = "SAVE_NWESLETTER_QUERY";
export const SAVE_NWESLETTER_QUERY_SUCCESS = "SAVE_NWESLETTER_QUERY_SUCCESS";
export const SAVE_NWESLETTER_QUERY_FAILED = "SAVE_NWESLETTER_QUERY_FAILED";
// CONTACT
export const SAVE_CONTACT_QUERY = "SAVE_CONTACT_QUERY";
export const SAVE_CONTACT_QUERY_SUCCESS = "SAVE_CONTACT_QUERY_SUCCESS";
export const SAVE_CONTACT_QUERY_FAILED = "SAVE_CONTACT_QUERY_FAILED";
// Project request
export const SAVE_PROJECT_QUERY = "SAVE_PROJECT_QUERY";
export const SAVE_PROJECT_QUERY_SUCCESS = "SAVE_PROJECT_QUERY_SUCCESS";
export const SAVE_PROJECT_QUERY_FAILED = "SAVE_PROJECT_QUERY_FAILED";
// Job Application (careers)
// actionTypes.js
export const SAVE_JOB_QUERY = "SAVE_JOB_QUERY";
export const SAVE_JOB_QUERY_SUCCESS = "SAVE_JOB_QUERY_SUCCESS";
export const SAVE_JOB_QUERY_FAILED = "SAVE_JOB_QUERY_FAILED";
